-- Restricciones extraídas del catálogo de producción, tal cual.
alter table public.budgets add constraint budgets_pkey PRIMARY KEY (id);
alter table public.clients add constraint clients_pkey PRIMARY KEY (id);
alter table public.delivery_notes add constraint delivery_notes_pkey PRIMARY KEY (id);
alter table public.document_versions add constraint document_versions_pkey PRIMARY KEY (id);
alter table public.expense_categories add constraint expense_categories_pkey PRIMARY KEY (id);
alter table public.invoice_items add constraint invoice_items_pkey PRIMARY KEY (id);
alter table public.invoices add constraint invoices_pkey PRIMARY KEY (id);
alter table public.payments add constraint payments_pkey PRIMARY KEY (id);
alter table public.portal_tokens add constraint portal_tokens_pkey PRIMARY KEY (id);
alter table public.project_changes add constraint project_changes_pkey PRIMARY KEY (id);
alter table public.project_milestones add constraint project_milestones_pkey PRIMARY KEY (id);
alter table public.projects add constraint projects_pkey PRIMARY KEY (id);
alter table public.received_invoices add constraint received_invoices_pkey PRIMARY KEY (id);
alter table public.suppliers add constraint suppliers_pkey PRIMARY KEY (id);
alter table public.budgets add constraint budgets_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL;
alter table public.budgets add constraint budgets_deposit_percent_range CHECK (((deposit_percent >= (0)::numeric) AND (deposit_percent <= (100)::numeric)));
alter table public.budgets add constraint budgets_discount_type_check CHECK ((discount_type = ANY (ARRAY['percent'::text, 'amount'::text])));
alter table public.budgets add constraint budgets_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE SET NULL;
alter table public.budgets add constraint budgets_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.budgets add constraint ck_budgets_lock_version_positive CHECK ((lock_version >= 1));
alter table public.clients add constraint clients_status_check CHECK ((status = ANY (ARRAY['active'::text, 'inactive'::text, 'lead'::text])));
alter table public.clients add constraint clients_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.delivery_notes add constraint delivery_notes_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE SET NULL;
alter table public.delivery_notes add constraint delivery_notes_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE SET NULL;
alter table public.delivery_notes add constraint delivery_notes_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE SET NULL;
alter table public.delivery_notes add constraint delivery_notes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);
alter table public.document_versions add constraint document_versions_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES auth.users(id);
alter table public.document_versions add constraint document_versions_entity_type_entity_id_version_key UNIQUE (entity_type, entity_id, version);
alter table public.expense_categories add constraint expense_categories_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.invoice_items add constraint invoice_items_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE;
alter table public.invoices add constraint invoices_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL;
alter table public.invoices add constraint invoices_payment_status_check CHECK ((payment_status = ANY (ARRAY['pending'::text, 'paid'::text, 'overdue'::text, 'cancelled'::text])));
alter table public.invoices add constraint invoices_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE SET NULL;
alter table public.invoices add constraint invoices_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES suppliers(id);
alter table public.invoices add constraint invoices_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);
alter table public.payments add constraint payments_budget_id_fkey FOREIGN KEY (budget_id) REFERENCES budgets(id);
alter table public.payments add constraint payments_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id);
alter table public.payments add constraint payments_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
alter table public.payments add constraint payments_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'completed'::text, 'cancelled'::text])));
alter table public.payments add constraint payments_type_check CHECK ((type = ANY (ARRAY['income'::text, 'expense'::text])));
alter table public.payments add constraint payments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);
alter table public.portal_tokens add constraint portal_tokens_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
alter table public.portal_tokens add constraint portal_tokens_expiry_window_check CHECK (((expires_at > created_at) AND (expires_at <= (created_at + portal_token_max_lifetime()))));
alter table public.portal_tokens add constraint portal_tokens_permissions_check CHECK (portal_token_permissions_valid(permissions));
alter table public.portal_tokens add constraint portal_tokens_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
alter table public.portal_tokens add constraint portal_tokens_token_key UNIQUE (token);
alter table public.project_changes add constraint project_changes_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
alter table public.project_changes add constraint project_changes_status_check CHECK ((status = ANY (ARRAY['proposed'::text, 'approved'::text, 'rejected'::text, 'executed'::text])));
alter table public.project_changes add constraint project_changes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);
alter table public.project_milestones add constraint project_milestones_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
alter table public.projects add constraint projects_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL;
alter table public.received_invoices add constraint received_invoices_category_id_fkey FOREIGN KEY (category_id) REFERENCES expense_categories(id) ON DELETE SET NULL;
alter table public.received_invoices add constraint received_invoices_payment_status_check CHECK ((payment_status = ANY (ARRAY['unpaid'::text, 'partial'::text, 'paid'::text])));
alter table public.received_invoices add constraint received_invoices_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'paid'::text, 'partial'::text, 'rejected'::text, 'overdue'::text])));
alter table public.received_invoices add constraint received_invoices_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE SET NULL;
alter table public.received_invoices add constraint received_invoices_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.suppliers add constraint suppliers_rating_check CHECK (((rating >= 0) AND (rating <= 5)));
alter table public.suppliers add constraint suppliers_status_check CHECK ((status = ANY (ARRAY['active'::text, 'inactive'::text])));
alter table public.suppliers add constraint suppliers_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);
