/**
 * verify-bc3-parser.ts
 *
 * Verification script for the BC3/FIEBDC-3 parser.
 * Tests parsing only — no Supabase, no network, no side effects.
 *
 * Run with: npx --yes tsx scripts/verify-bc3-parser.ts
 */

import * as fs from "fs";
import * as path from "path";
import { parseBC3, classifyConcepts, inferComponentType } from "../lib/bc3-parser";

// ─── Helpers ────────────────────────────────────────────────────────────────

let passed = 0;
let failed = 0;

function assert(condition: boolean, label: string, detail?: string): void {
  if (condition) {
    console.log(`  ✅ ${label}`);
    passed++;
  } else {
    console.log(`  ❌ ${label}${detail ? ` — ${detail}` : ""}`);
    failed++;
  }
}

function assertEq<T>(actual: T, expected: T, label: string): void {
  if (actual === expected) {
    console.log(`  ✅ ${label} (${JSON.stringify(actual)})`);
    passed++;
  } else {
    console.log(`  ❌ ${label}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(actual)}`);
    failed++;
  }
}

function section(title: string): void {
  console.log(`\n── ${title} ${"─".repeat(60 - title.length)}`);
}

// ─── Load fixture ───────────────────────────────────────────────────────────

console.log("BC3 Parser Verification Script");
console.log("==============================\n");

const fixturePath = path.join(__dirname, "fixtures", "sample-technical-bank.bc3");

if (!fs.existsSync(fixturePath)) {
  console.error(`Fixture not found: ${fixturePath}`);
  process.exit(1);
}

const content = fs.readFileSync(fixturePath, "utf-8");
console.log(`Loaded fixture: ${fixturePath} (${content.length} bytes)`);

// ─── Test 1: Basic parsing ──────────────────────────────────────────────────

section("1. Basic parsing");

const parsed = parseBC3(content);

assert(parsed.concepts.length > 0, "Parsed concepts exist");
assert(parsed.decompositions.length > 0, "Parsed decompositions exist");
assert(parsed.longTexts.length > 0, "Parsed long texts exist");
assert(parsed.stats.totalLines > 0, "Total lines counted");
assert(parsed.stats.parsedRecords > 0, "Parsed records counted");

// ─── Test 2: Metadata extraction ────────────────────────────────────────────

section("2. Metadata extraction");

assertEq(parsed.metadata.fiebdcVersion, "FIEBDC-3/2020", "FIEBDC version");
assertEq(parsed.metadata.generatedBy, "ENLAZE-test", "Generated by");
assertEq(parsed.metadata.currency, "EUR", "Currency");

// ─── Test 3: Chapter extraction ─────────────────────────────────────────────

section("3. Chapter extraction");

const classified = classifyConcepts(parsed);

// Chapters: 01, 01.01, 02, 03 = 4 chapters (ROOT is excluded)
assertEq(classified.chapterCodes.size, 4, "Chapter count");
assert(classified.chapterCodes.has("01"), "Chapter 01 exists");
assert(classified.chapterCodes.has("01.01"), "Chapter 01.01 (subcapitulo) exists");
assert(classified.chapterCodes.has("02"), "Chapter 02 exists");
assert(classified.chapterCodes.has("03"), "Chapter 03 exists");

// Root detection
assert(classified.rootCodes.length === 1, "Exactly 1 root");
assertEq(classified.rootCodes[0], "ROOT", "Root code is ROOT");

// ─── Test 4: Chapter hierarchy ──────────────────────────────────────────────

section("4. Chapter hierarchy");

assertEq(classified.chapterDepth.get("01"), 1, "Chapter 01 depth = 1");
assertEq(classified.chapterDepth.get("01.01"), 2, "Chapter 01.01 depth = 2");
assertEq(classified.chapterDepth.get("02"), 1, "Chapter 02 depth = 1");
assertEq(classified.chapterDepth.get("03"), 1, "Chapter 03 depth = 1");

// Parent-child: 01.01 is child of 01
assertEq(classified.chapterParent.get("01.01"), "01", "01.01 parent is 01");

// ─── Test 5: Partida extraction ─────────────────────────────────────────────

section("5. Partida (item) extraction");

// Items with decomposition: 01.01.001, 01.01.002, 02.001, 03.001
assertEq(classified.itemCodes.size, 4, "Item count");
assert(classified.itemCodes.has("01.01.001"), "Item 01.01.001 exists");
assert(classified.itemCodes.has("01.01.002"), "Item 01.01.002 exists");
assert(classified.itemCodes.has("02.001"), "Item 02.001 exists");
assert(classified.itemCodes.has("03.001"), "Item 03.001 exists");

// ─── Test 6: Resource extraction ────────────────────────────────────────────

section("6. Resource (component) extraction");

// Resources: MO001-MO004, MA001-MA008, AUX01, MQ001 = 14
assertEq(classified.resourceCodes.size, 14, "Resource count");
assert(classified.resourceCodes.has("MO001"), "MO001 (Oficial albanil) exists");
assert(classified.resourceCodes.has("MA001"), "MA001 (Ladrillo) exists");
assert(classified.resourceCodes.has("MQ001"), "MQ001 (Hormigonera) exists");
assert(classified.resourceCodes.has("AUX01"), "AUX01 (Medios auxiliares) exists");

// ─── Test 7: Units preserved ────────────────────────────────────────────────

section("7. Unit preservation");

const conceptMap = new Map(parsed.concepts.map(c => [c.code, c]));

assertEq(conceptMap.get("01.01.001")?.unit, "m2", "01.01.001 unit = m2");
assertEq(conceptMap.get("02.001")?.unit, "ud", "02.001 unit = ud");
assertEq(conceptMap.get("MO001")?.unit, "h", "MO001 unit = h");
assertEq(conceptMap.get("MA001")?.unit, "ud", "MA001 unit = ud");
assertEq(conceptMap.get("MA002")?.unit, "m3", "MA002 unit = m3");
assertEq(conceptMap.get("MA003")?.unit, "ml", "MA003 unit = ml");

// ─── Test 8: Prices preserved ───────────────────────────────────────────────

section("8. Price preservation");

assertEq(conceptMap.get("01.01.001")?.price, 28.45, "01.01.001 price = 28.45");
assertEq(conceptMap.get("01.01.002")?.price, 14.80, "01.01.002 price = 14.80");
assertEq(conceptMap.get("MO001")?.price, 19.50, "MO001 price = 19.50");
assertEq(conceptMap.get("MA001")?.price, 0.12, "MA001 price = 0.12");
assertEq(conceptMap.get("MQ001")?.price, 1.80, "MQ001 price = 1.80");

// ─── Test 9: Component type inference ───────────────────────────────────────

section("9. Component type inference");

assertEq(inferComponentType(conceptMap.get("MO001")!), "labor", "MO001 = labor (type=1)");
assertEq(inferComponentType(conceptMap.get("MO002")!), "labor", "MO002 = labor (type=1)");
assertEq(inferComponentType(conceptMap.get("MA001")!), "material", "MA001 = material (type=3)");
assertEq(inferComponentType(conceptMap.get("MQ001")!), "machinery", "MQ001 = machinery (type=2)");
assertEq(inferComponentType(conceptMap.get("AUX01")!), "auxiliary", "AUX01 = auxiliary (unit=%)");

// ─── Test 10: Decomposition yields ─────────────────────────────────────────

section("10. Decomposition yields (rendimientos)");

const decompMap = new Map(parsed.decompositions.map(d => [d.parentCode, d]));

const tabique = decompMap.get("01.01.001");
assert(tabique !== undefined, "01.01.001 has decomposition");
assertEq(tabique?.children.length, 6, "01.01.001 has 6 components");

// Check specific yields
const mo001InTabique = tabique?.children.find(c => c.childCode === "MO001");
assertEq(mo001InTabique?.quantityPerUnit, 0.55, "MO001 yield in tabique = 0.55 h/m2");

const ma001InTabique = tabique?.children.find(c => c.childCode === "MA001");
assertEq(ma001InTabique?.quantityPerUnit, 42.0, "MA001 yield in tabique = 42.0 ud/m2");

const mq001InTabique = tabique?.children.find(c => c.childCode === "MQ001");
assertEq(mq001InTabique?.quantityPerUnit, 0.05, "MQ001 yield in tabique = 0.05 h/m2");

// ─── Test 11: Cost calculation from components ─────────────────────────────

section("11. Cost calculation from decomposition");

// 01.01.001 Tabique: MO001*0.55 + MO002*0.55 + MA001*42 + MA002*0.012 + AUX01*2.0 + MQ001*0.05
// = 19.50*0.55 + 16.20*0.55 + 0.12*42 + 68.50*0.012 + 2.00*2.0 + 1.80*0.05
// = 10.725 + 8.91 + 5.04 + 0.822 + 4.0 + 0.09
// = 29.587
const tabChildren = decompMap.get("01.01.001")?.children || [];
let calculatedCost = 0;
for (const child of tabChildren) {
  const concept = conceptMap.get(child.childCode);
  if (concept) {
    calculatedCost += child.quantityPerUnit * concept.price;
  }
}
const roundedCost = Math.round(calculatedCost * 100) / 100;
console.log(`  Calculated cost from components: ${roundedCost} EUR/m2`);
console.log(`  Declared price:                  ${conceptMap.get("01.01.001")?.price} EUR/m2`);
assert(
  Math.abs(roundedCost - 29.59) < 0.02,
  `Calculated cost ~29.59 (got ${roundedCost})`
);

// ─── Test 12: Long text extraction ──────────────────────────────────────────

section("12. Long text extraction");

assertEq(parsed.longTexts.length, 3, "3 long texts parsed");
const lt001 = parsed.longTexts.find(t => t.code === "01.01.001");
assert(lt001 !== undefined, "01.01.001 has long text");
assert(
  lt001?.text.includes("Tabique de ladrillo cerámico") === true,
  "Long text contains accented characters"
);
assert(
  lt001?.text.includes("CTE DB-HR") === true,
  "Long text preserves technical references"
);

// ─── Test 13: Error handling ────────────────────────────────────────────────

section("13. Error and warning handling");

assert(parsed.warnings.length > 0, "Warnings were generated");

// Check for the ~M unsupported record warning
const mWarning = parsed.warnings.find(w => w.record === "~M");
assert(mWarning !== undefined, "~M record generated warning");
assert(
  mWarning?.message.includes("Unsupported") === true,
  "~M warning says unsupported"
);

// Check for malformed line
const malformed = parsed.warnings.find(w => w.record === "?");
assert(malformed !== undefined, "Malformed line generated warning");

// Verify error count in stats
assert(parsed.stats.errorLines > 0, "Error lines counted");
assert(parsed.stats.skippedRecords > 0, "Skipped records counted");

// ─── Test 14: Encoding / accents ────────────────────────────────────────────

section("14. Encoding and accent handling");

const albanileria = conceptMap.get("01");
assert(
  albanileria?.summary.includes("Albañilería") === true,
  "ñ preserved in chapter name"
);

const electricidad = conceptMap.get("03");
assert(
  electricidad?.summary.includes("iluminación") === true,
  "ó preserved in chapter name"
);

const fontanero = conceptMap.get("MO003");
assert(
  fontanero?.summary.includes("fontanero") === true,
  "fontanero name correct"
);

// ─── Test 15: Empty / edge cases ────────────────────────────────────────────

section("15. Edge cases");

// Parse empty string
const emptyResult = parseBC3("");
assertEq(emptyResult.concepts.length, 0, "Empty string → 0 concepts");
assertEq(emptyResult.warnings.length, 0, "Empty string → 0 warnings");
assertEq(emptyResult.stats.parsedRecords, 0, "Empty string → 0 parsed records");

// Parse string with only unsupported records
const unsupported = parseBC3("~M|data|medicion|\n~W|geo|data|\n");
assertEq(unsupported.concepts.length, 0, "Only unsupported → 0 concepts");
assertEq(unsupported.stats.skippedRecords, 2, "Only unsupported → 2 skipped");

// Parse minimal valid BC3
const minimal = parseBC3("~C|TEST01|m2|Partida de prueba|25.00||3|\n");
assertEq(minimal.concepts.length, 1, "Minimal BC3 → 1 concept");
assertEq(minimal.concepts[0].price, 25.0, "Minimal BC3 → price 25.00");

// ─── Summary ────────────────────────────────────────────────────────────────

console.log("\n══════════════════════════════════════════════════════════════");
console.log(`Results: ${passed} passed, ${failed} failed, ${passed + failed} total`);

if (failed > 0) {
  console.log("\n⚠️  Some tests failed. Review the output above.");
  process.exit(1);
} else {
  console.log("\n✅ All tests passed.");
  process.exit(0);
}
